### ISSUE TITLE
I can't run it 

### ISSUE THREAD

**Issue by brothermechanic** [rigred/lithosphere-fork#1]
when i run setup.py
```
$ ./setup.py 
./setup.py: line 11: $'\n    lithosphere\n    ~~~~~~~~~~~\n\n    A GPU terrain generator\n\n    :copyright: 2010 by Florian Boesch <pyalot@gmail.com>.\n    :license: GNU AGPL v3 or later, see LICENSE for more details.\n': command not found
from: using legacy configuration file /etc/mailutils.rc: please rename it to /etc/mailutils.conf
from: too many arguments
./setup.py: line 15: syntax error near unexpected token `newline'
./setup.py: line 15: `setup('
```

when i run run.py
$ ./run.py 
```
Traceback (most recent call last):
  File "./run.py", line 11, in <module>
    main()
  File "/home/bm/bin/lithosphere/dist/lithosphere/lithosphere-0.1.0-py2.6.egg/lithosphere/application.py", line 201, in main
  File "/home/bm/bin/lithosphere/dist/lithosphere/lithosphere-0.1.0-py2.6.egg/lithosphere/application.py", line 46, in __init__
  File "/home/bm/bin/lithosphere/dist/lithosphere/halogen-0.1.1-py2.6.egg/halogen/root.py", line 25, in __init__
  File "/home/bm/bin/lithosphere/dist/lithosphere/halogen-0.1.1-py2.6.egg/halogen/style.py", line 73, in __init__
  File "/home/bm/bin/lithosphere/dist/lithosphere/halogen-0.1.1-py2.6.egg/halogen/hss.py", line 203, in parse
  File "/home/bm/bin/lithosphere/dist/lithosphere/halogen-0.1.1-py2.6.egg/halogen/hss.py", line 193, in rule
  File "/home/bm/bin/lithosphere/dist/lithosphere/halogen-0.1.1-py2.6.egg/halogen/style.py", line 84, in convert
  File "/home/bm/bin/lithosphere/dist/lithosphere/halogen-0.1.1-py2.6.egg/halogen/attributes.py", line 122, in convert_attributes
  File "/home/bm/bin/lithosphere/dist/lithosphere/halogen-0.1.1-py2.6.egg/halogen/attributes.py", line 64, in background
  File "/home/bm/bin/lithosphere/dist/lithosphere/halogen-0.1.1-py2.6.egg/halogen/resources.py", line 76, in patch
  File "/home/bm/bin/lithosphere/dist/lithosphere/pyglet-1.2dev-py2.6.egg/pyglet/image/__init__.py", line 192, in load
io.UnsupportedOperation: seek

```
my system is asus g75-vw gentoo-os amd64

**Comment by rigred** [comment]
This repo purely exists here for legacy(archival) purposes but I will have a look at the issue. There are likely a few python2 to python3 conversion issues and possibly broken dependencies nowadays.
